2025-04-22 10:48:56,255 - Graphiant_playbook - INFO - PortalUtils : templates_path : /Users/keshav/ws/graphiant-playbooks/configs/
2025-04-22 10:48:56,255 - Graphiant_playbook - INFO - PortalUtils : config_templates : /Users/keshav/ws/graphiant-playbooks/templates/
2025-04-22 10:48:56,255 - Graphiant_playbook - INFO - PortalUtils : logs_path : /Users/keshav/ws/graphiant-playbooks/logs/
2025-04-22 10:48:58,223 - Graphiant_playbook - INFO - Poller attempt: 1/12
2025-04-22 10:48:58,223 - Graphiant_playbook - INFO - Poller attempt: 1/12
2025-04-22 10:48:58,223 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:48:58,223 - Graphiant_playbook - INFO - Poller attempt: 1/12
2025-04-22 10:48:58,223 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:48:58,224 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:48:58,348 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': 'true',
                                                                'lan': 'default-10000000288'}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': {'adminStatus': 'true',
                                                                                                       'lan': 'default-10000000288',
                                                                                                       'vlan': 18}}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:48:58,539 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051082: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': 'true',
                                                                'lan': 'default-10000000288'}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'lan': 'default-10000000288'}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:48:58,541 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051081: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': 'true',
                                                                'lan': 'default-10000000288'}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'28': {'interface': {'adminStatus': 'true',
                                                                                                       'lan': 'default-10000000288',
                                                                                                       'vlan': 28}}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:01,085 - Graphiant_playbook - INFO - Poller attempt: 1/12
2025-04-22 10:49:01,085 - Graphiant_playbook - INFO - Poller attempt: 1/12
2025-04-22 10:49:01,085 - Graphiant_playbook - INFO - Poller attempt: 1/12
2025-04-22 10:49:01,085 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:01,085 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:01,085 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:01,373 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051082: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:01,382 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:01,382 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:01,382 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:01,386 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:01,509 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (428)
Reason: Precondition Required
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:48:43 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '298', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"12a-LZOy3Z0hMW/ZOxM72wTCbl7k4nU"', 'Set-Cookie': 'connect.sid=s%3AfZsmtS_uYrw60j7jW8e7mrbNrVx_KD5d.LxRVOWrfK1zrcOrMDz4%2F7%2BkDn9GxBMc7ohWfblSGRSY; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":9,"displayError":"this device is not ready for a configuration push. Please retry again in some time. Consider creating a draft configuration","detailedError":"this device is not ready for a configuration push. Please retry again in some time. Consider creating a draft configuration"}'

2025-04-22 10:49:01,510 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051082
2025-04-22 10:49:01,510 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:01,542 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (428)
Reason: Precondition Required
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:48:43 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '298', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"12a-LZOy3Z0hMW/ZOxM72wTCbl7k4nU"', 'Set-Cookie': 'connect.sid=s%3A7IHrdlvusPSngYF9JqICNc2V9IBM-R43.YfCDjbMksDs7BmdKUl6gGYlnOJn85TB%2BWW5842E7UAk; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":9,"displayError":"this device is not ready for a configuration push. Please retry again in some time. Consider creating a draft configuration","detailedError":"this device is not ready for a configuration push. Please retry again in some time. Consider creating a draft configuration"}'

2025-04-22 10:49:01,542 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:49:01,542 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:11,388 - Graphiant_playbook - INFO - Poller attempt: 2/12
2025-04-22 10:49:11,388 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:11,517 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:11,518 - Graphiant_playbook - INFO - Poller attempt: 2/12
2025-04-22 10:49:11,518 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:11,518 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:11,518 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:11,547 - Graphiant_playbook - INFO - Poller attempt: 2/12
2025-04-22 10:49:11,547 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:11,642 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051082 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:11,642 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051082 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:11,642 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:11,663 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051080 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:11,663 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051080 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:11,663 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:21,524 - Graphiant_playbook - INFO - Poller attempt: 3/12
2025-04-22 10:49:21,524 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:21,640 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:21,640 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:21,641 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:21,647 - Graphiant_playbook - INFO - Poller attempt: 3/12
2025-04-22 10:49:21,647 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:21,667 - Graphiant_playbook - INFO - Poller attempt: 3/12
2025-04-22 10:49:21,667 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:21,763 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051082 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:21,763 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051082 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:21,763 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:21,786 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051080 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:21,786 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051080 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:21,786 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:31,642 - Graphiant_playbook - INFO - Poller attempt: 4/12
2025-04-22 10:49:31,643 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:31,764 - Graphiant_playbook - INFO - Poller attempt: 4/12
2025-04-22 10:49:31,764 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:31,766 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:31,766 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051081 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:31,766 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:31,791 - Graphiant_playbook - INFO - Poller attempt: 4/12
2025-04-22 10:49:31,791 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:31,873 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051082 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:31,873 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051082 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:31,873 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:31,903 - Graphiant_playbook - INFO - put_device_config : Retrying,  30000051080 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:31,903 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying,  30000051080 Portal Status: Configuring (Expected Ready)
2025-04-22 10:49:31,903 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:41,772 - Graphiant_playbook - INFO - Poller attempt: 5/12
2025-04-22 10:49:41,772 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:41,878 - Graphiant_playbook - INFO - Poller attempt: 5/12
2025-04-22 10:49:41,878 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:41,899 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051081: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'28': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:41,908 - Graphiant_playbook - INFO - Poller attempt: 5/12
2025-04-22 10:49:41,908 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:42,024 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051082: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:42,044 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:44,132 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:49:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '293', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"125-1NxS5BYuyY40aYH/gQ/aDINMVfQ"', 'Set-Cookie': 'connect.sid=s%3AQH9eIdL1vbS1CGjU_fDjR1vxMUJE_gf8.V%2FfYdDPFOOBgDLGqVOCcy1jZxMK4OcURubde7CElyO8; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":13,"displayError":"schema: unable to insert into configuration: read tcp 10.244.1.156:36014->10.67.4.5:5432: read: connection reset by peer","detailedError":"schema: unable to insert into configuration: read tcp 10.244.1.156:36014->10.67.4.5:5432: read: connection reset by peer"}'

2025-04-22 10:49:44,132 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:49:44,132 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:49:54,137 - Graphiant_playbook - INFO - Poller attempt: 6/12
2025-04-22 10:49:54,138 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:49:54,262 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:49:54,987 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:49:36 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3A57uPcI5sDnGfxNgRlCSl48utm3iZu7bX.Un01j9JHtO3N7Vcq%2BaJb1zsr0DAdTOl8iX%2FaDng6rWM; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:49:54,987 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:49:54,987 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:50:04,993 - Graphiant_playbook - INFO - Poller attempt: 7/12
2025-04-22 10:50:04,994 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:50:05,119 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:50:05,841 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:49:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3AEKcRE0r1kfRt1VI7is2_t92CpXIxgVU-.siA3GCQwnu1mo2hJM0Mp4eRNNyz5A4Z75vsVxnaeJPc; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:50:05,842 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:50:05,842 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:50:15,843 - Graphiant_playbook - INFO - Poller attempt: 8/12
2025-04-22 10:50:15,844 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:50:15,968 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:50:16,615 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:49:58 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3AZJL-P2ZobKOeZSyCf5UiUyeu7FWGntfB.BEreEz1gBrDon%2BhLZKKCre1l%2BmR8kPwELF2A2squmqs; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:50:16,615 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:50:16,615 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:50:26,619 - Graphiant_playbook - INFO - Poller attempt: 9/12
2025-04-22 10:50:26,619 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:50:26,745 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:50:27,447 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:50:09 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3AMIBnp_MkGCT9FHnM4s2LGZHBWJ69fcdy.YrHT%2BJ%2FuWHmxKShmxCueBH%2FTw%2F%2FwusNsw%2FcQQf9Nz14; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:50:27,447 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:50:27,447 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:50:37,451 - Graphiant_playbook - INFO - Poller attempt: 10/12
2025-04-22 10:50:37,452 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:50:37,571 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:50:38,300 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:50:20 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3A8aAJpYVLNjBDFUCSBCyDWoXPVYcIUE7c.eLbLCMan%2Be0Y0bZkTCMClbmH4JQ%2Bat6sMXzQvrfoJ8E; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:50:38,301 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:50:38,301 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:50:48,305 - Graphiant_playbook - INFO - Poller attempt: 11/12
2025-04-22 10:50:48,306 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:50:48,430 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:50:49,156 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:50:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3Ak0Z4RbVcqemCLahFpmpq_J2N3dulBbLe.aXa8kERUfSQk3MWG6tBEzy31%2B7MRSx87yjXiS64XI1Q; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:50:49,157 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:50:49,157 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:50:59,157 - Graphiant_playbook - INFO - Poller attempt: 12/12
2025-04-22 10:50:59,159 - Graphiant_playbook - INFO - Calling method put_device_config()...
2025-04-22 10:50:59,277 - Graphiant_playbook - INFO - put_device_config : config to be pushed for 30000051080: 
{'configuration_metadata': None,
 'core': None,
 'description': None,
 'edge': {'interfaces': {'GigabitEthernet5/0/0': {'interface': {'adminStatus': False,
                                                                'alias': '',
                                                                'description': '',
                                                                'maxTransmissionUnit': 1500}},
                         'GigabitEthernet8/0/0': {'interface': {'adminStatus': 'true',
                                                                'subinterfaces': {'18': {'interface': None}}}}}},
 'local_web_server_password': None,
 'replace': None}
2025-04-22 10:50:59,925 - Graphiant_playbook - WARNING - put_device_config : Exception While config push (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:50:41 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3AOoon_ictcoHqqU_ReTvZN4Yc6HbzSu1p.qpJp3PYwdgfjzTM1V784q6vDRJG6hslkmTjYKAyrxoM; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'

2025-04-22 10:50:59,925 - Graphiant_playbook - INFO - Exception caught while calling method put_device_config(): put_device_config : Retrying, Exception while config push to 30000051080
2025-04-22 10:50:59,925 - Graphiant_playbook - INFO - Sleeping for 10 seconds before retry...
2025-04-22 10:51:10,126 - Graphiant_playbook - WARNING - Traceback (most recent call last):
  File "/Users/keshav/ws/graphiant-playbooks/libs/gcsdk_client.py", line 59, in put_device_config
    response = self.api.v1_devices_device_id_config_put(authorization=self.bearer_token,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/api/default_api.py", line 12583, in v1_devices_device_id_config_put
    (data) = self.v1_devices_device_id_config_put_with_http_info(device_id, **kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/api/default_api.py", line 12653, in v1_devices_device_id_config_put_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/api_client.py", line 148, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/api_client.py", line 366, in request
    return self.rest_client.PUT(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/rest.py", line 274, in PUT
    return self.request("PUT", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/venv/lib/python3.12/site-packages/swagger_client/rest.py", line 223, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 22 Apr 2025 17:50:41 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '184', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Access-Control-Allow-Methods': 'PATCH, DELETE, PUT, GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Pragma, Authorization, Content-Type, Accept, Expires, Referer, Cache-Control, Baggage, Sentry-Trace', 'Content-Security-Policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests", 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Resource-Policy': 'same-origin', 'Origin-Agent-Cluster': '?1', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '0', 'ETag': 'W/"b8-DKXY4/9hA+3dKW2AhPoIuOpF13A"', 'Set-Cookie': 'connect.sid=s%3AOoon_ictcoHqqU_ReTvZN4Yc6HbzSu1p.qpJp3PYwdgfjzTM1V784q6vDRJG6hslkmTjYKAyrxoM; Path=/; HttpOnly'})
HTTP response body: b'{"errorCode":5,"displayError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set","detailedError":"error deleting GigabitEthernet8/0/0.18: sql: no rows in result set"}'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keshav/ws/graphiant-playbooks/libs/poller.py", line 96, in retry_poller
    return fun(*fun_args, **fun_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keshav/ws/graphiant-playbooks/libs/gcsdk_client.py", line 67, in put_device_config
    assert False, f"put_device_config : Retrying, Exception while config push to {device_id}"
           ^^^^^
AssertionError: put_device_config : Retrying, Exception while config push to 30000051080

2025-04-22 10:51:10,127 - Graphiant_playbook - ERROR - future failed: put_device_config : Retrying, Exception while config push to 30000051080
